
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480

GROUND_LEVEL = 300
GROUND_HEIGHT = SCREEN_HEIGHT - GROUND_LEVEL
GROUND_POSITION = 0, SCREEN_HEIGHT - GROUND_HEIGHT, SCREEN_WIDTH, SCREEN_HEIGHT
GROUND_COLOR = 191, 128, 64